### ISSUE TITLE
Can we use this library in terminal.. Does is support pure dart?

### ISSUE THREAD

**Issue by Akaatsukhi** [modwedar/YoutubeDataApi#1]

**Comment by modwedar** [comment]
Yes, You can

**Comment by Akaatsukhi** [comment]
How to get particular youtube video link from searching query

**Comment by modwedar** [comment]
You can get video id then get youtube link
String query = "Query";
YoutubeDataApi youtubeDataApi = YoutubeDataApi();
List videoResult = await youtubeDataApi.fetchSearchVideo(query);
videoResult.forEach((element){
    if(element is Video){
      Video video = element;
      String? id = video.videoId;
      String link = "https://www.youtube.com/watch?v=$id";
    }
});

**Comment by Akaatsukhi** [comment]
Cool.. i like it that package is simple and straightforward...but still this section might not be the proper place to ask my doubt
Are you reachable via twitter of email
