### ISSUE TITLE
Trending Videos, music, gaming,movies ...... Thumbnail is null

### ISSUE THREAD

**Issue by thivankasarathchandra** [modwedar/YoutubeDataApi#2]
HI, All other data can be accessed but not the thumbnail data. I assume the String is the thumbnail url.

`snapshot.data![index].thumbnail!.toString()`

Tried to access it like this . but the results are null.

**Comment by modwedar** [comment]
You can use String thumbnail = "https://i.ytimg.com/vi/$videoId/hqdefault.jpg";
The problem will be resolved in the next version

**Comment by modwedar** [comment]
Now you can update to youtube_data_api: ^1.0.4
