### ISSUE TITLE
Hii brother

### ISSUE THREAD

**Issue by Harshhvermaa** [modwedar/YoutubeDataApi#3]
The current Dart SDK version is 2.17.0.

Because youtube_video_linker requires SDK version >=2.17.1 <3.0.0, version solving failed.
pub get failed (1; Because youtube_video_linker requires SDK version >=2.17.1 <3.0.0, version solving failed.)
exit code 1

**Comment by Harshhvermaa** [comment]
This package is not istalling on my system can you please help me to fix it

**Comment by modwedar** [comment]
You have to upgrade flutter with flutter upgrade command. Then flutter will use latest version of Dart SDK.

**Comment by Harshhvermaa** [comment]
ok will check
